### ISSUE TITLE
undefined

### ISSUE THREAD

**Issue by icusick** [icusick/project1#1]
this is a for loop that i'm using in the function that gets the computer to light up the buttons:
for (var i = 0; i < $computerArray.length; i++) {
        setTimeout(function() { $computerArray[i].addClass('hidden') }, i*200);
        setTimeout(function() { $computerArray[i].removeClass('hidden') }, 200);
                }
 i'm getting an error that says it cannot add a class to undefined:
Uncaught TypeError: Cannot read property 'addClass' of undefined(anonymous function) @ main.js:43
Uncaught TypeError: Cannot read property 'removeClass' of undefined(anonymous function) @ main.js:44

but $computerArray is NOT undefined, it's very defined in fact, and the console acts like it knows what   $computerArray is when i ask it, including specific indexes of $computerArray, but then it tell me it's undefined when i try to add or remove a class to it! 

why?

**Comment by icusick** [comment]
are you the right assignee? or should it be the instructor we met with today?

**Comment by phlco** [comment]
This is fine! Please update your issue so that your code snippets are in "code fences" put three backticks at the top and bottom of the code.

It's the difference between this:

for (var i = 0; i < $computerArray.length; i++) {
setTimeout(function() { $computerArray[i].addClass('hidden') }, i*200);
setTimeout(function() { $computerArray[i].removeClass('hidden') }, 200);
}

and this

``` js
for (var i = 0; i < $computerArray.length; i++) {
  // note the correct indentation too!
  setTimeout(function() {
    // include a new line after the opening curly brace in a function
    $computerArray[i].addClass('hidden') 
  }, i*200);
  setTimeout(function() { 
    $computerArray[i].removeClass('hidden') 
  }, 200);
}
```

**Comment by phlco** [comment]
What's happening is you're calling `setTimeout` in a loop and passing it a variable. 

We'd all think that `setTimeout` would get called a bunch of times in the loop and each time `i` would be something different.

However! The loop runs and when it's over `i` is now whatever the final number is and then all the `setTimeouts` run and they're all pointing at the same value for `i`

So let's say you have an array with 4 things in it. When the loop is done `i` will be `4` and then we're trying to access the `4` thing in the array which is one too many so it'll be undefined.

If you want to preserve the value of `i` for each `setInterval` you'll need a way to preserve the value at that time. One way to do that is to pass `i` inside a function, because that creates another scope.

**Comment by icusick** [comment]
thanks!
